// 목소리 — 도구의 말투. 일어난 일만 짧게 적고, 위로하거나 감탄하지 않는다.
export const S = {
  appName: '밑줄',
  tagline: '적기만 하는 기록 말고, 구조가 붙는 기록',

  tab_today: '수집함',
  tab_library: '기록',
  tab_capture: '적기',
  tab_trends: '지표',
  tab_review: '검토',

  compose_title: '무엇을 남길까요?',
  compose_save: '밑줄 긋기',
  compose_close: '닫기',
  compose_stop: '그만 긋기',
  compose_nth: (n: number) => `${n}개째`,
  compose_new_source: (label: string) => `+ 새 ${label}`,
  compose_add_tags: '+ 태그',
  compose_add_memo: '+ 메모',
  compose_video_hint: '링크를 붙여넣거나 메모를 남기면 돼요.',
  compose_video_hint_memo: '이 영상에 남길 메모를 적어요.',
  source_title_empty: '제목이 비어 있어요.',
  compose_link_placeholder: '링크를 붙여넣어요',
  compose_paste_clipboard: '클립보드의 링크 붙여넣기',
  compose_clipboard_empty: '클립보드에 링크가 없어요.',
  compose_link_reading: '링크를 읽는 중…',
  compose_link_known: '이미 담아둔 영상이에요 — 메모를 이어서 남겨요.',
  compose_legacy_source: (title: string) =>
    `${title ? `${title} · ` : ''}출처와 이어지지 않은 기록이에요 — 위에서 출처를 고르거나 새로 적으면 이어 붙어요.`,
  compose_edit_title: '제목 고치기',
  compose_no_link: '링크 없이 적기',
  video_open_external: '브라우저에서 열기',
  compose_day_prev: '하루 전',
  compose_day_next: '하루 뒤',
  source_rename: '이름 고치기',
  source_rename_done: '고치기 완료',
  source_delete: '출처 지우기',
  source_delete_title: '이 출처를 지울까요?',
  source_delete_body: '남긴 기록은 그대로 남아요.',
  compose_continuous_hint: (label: string) =>
    `저장해도 시트는 닫히지 않아요 — 같은 ${label}에 다음 기록을 바로 이어서.`,
  compose_flash: '저장됨',
  compose_tags_placeholder: '#태그 (띄어쓰기로 구분)',
  compose_photo_camera: '카메라',
  compose_photo_album: '앨범',
  compose_minutes_suffix: '분',
  compose_dropped_warning: '지금 유형에서는 저장되지 않는 내용이 있어요',

  save_done: '저장됨',
  save_task_done: '저장됨',

  empty_today: '오늘 기록 없음',
  empty_library: '기록 없음',
  empty_trends: '지표를 그리려면 며칠의 기록이 필요합니다',
  empty_tag: '이 갈피에 걸린 기록 없음',
  empty_search: '결과 없음',

  resurface_header: '다시 읽기',
  resurface_pinned_caption: '표시함',
  resurface_forgotten_caption: '오래 안 읽음',
  resurface_keep: '유지',
  resurface_retire: '순환에서 제외',
  resurface_kept_toast: '표시함에 추가됨',
  resurface_retired_toast: '순환에서 제외됨',

  library_search_placeholder: '문장 · 제목 · 갈피 검색',
  library_sort_recent: '최신순',
  library_sort_dusty: '오래 안 읽은 순',
  library_filter_pinned: '표시함',
  library_all: '전체',
  library_last_read: (n: number) => `${n}일 전 읽음`,
  library_never_read: '읽은 적 없음',

  detail_related: '같은 갈피',
  detail_pin: '표시',
  detail_pinned: '표시함',
  detail_delete: '삭제',
  detail_delete_title: '이 기록을 삭제할까요?',
  detail_delete_confirm: '삭제',
  detail_cancel: '취소',
  detail_edit: '편집',

  today_tasks: '할 일',
  today_task_placeholder: '할 일 추가',
  today_entries: '오늘',

  trends_practice_header: '실천',
  trends_week_workout: '이번 주 운동',
  trends_month_shelf: '이달의 형식',
  trends_streak: (name: string, n: number) => `${name} · ${n}일 연속`,
  trends_week_fallback: (name: string, n: number) => `${name} · 이번 주 ${n}일`,
  trends_rows: { workout: '운동', meal: '식사', verse: '묵상', record: '기록' },

  settings_title: '설정',
  settings_theme: '화면',
  settings_theme_system: '시스템',
  settings_theme_light: '밝게',
  settings_theme_dark: '어둡게',
  settings_export: '옵시디언으로 내보내기',
  settings_export_week: '이번 주',
  settings_export_month: '이번 달',
  settings_export_all: '전체',
  settings_about: '밑줄에 대해',

  export_action: '옵시디언으로 내보내기',
  export_done: '내보낼 파일이 준비됨',
  export_empty: '이 기간에 기록 없음',

  tag_bookend_first: '처음',
  tag_bookend_latest: '최근',

  onboarding_title: '밑줄',
  onboarding_body:
    '한 칸에 적으면 구조가 붙습니다.\n링크·쪽수·본문 주소·갈피를 앱이 읽어\n유형과 항목을 채웁니다.\n\n정리는 당신이 기억할 일이 아니라\n앱이 내미는 줄입니다.',
  onboarding_start: '시작',

  // ─── 캡처 ───
  capture_title: '새 기록',
  capture_count: (n: number) => `${n}건 저장됨`,
  capture_save: '저장',
  capture_done: '완료',
  capture_placeholder: '무엇이든 붙여넣거나 적으세요',
  capture_hint: '링크 · p.57 · 시편 23:1 · #갈피 · 30분 · 14:00 을 알아서 읽습니다',
  capture_source_label: '출처',
  capture_source_auto: '링크에서 자동',
  capture_source_none: '없음',
  capture_source_empty: '등록된 출처 없음',
  capture_discard_title: '작성 중인 기록이 있습니다',
  capture_discard_body: '닫으면 사라집니다.',
  capture_keep_writing: '계속 쓰기',
  capture_save_failed: '저장하지 못했습니다',

  // ─── 검토 ───
  review_title: '검토',
  review_unfiled: '구조 없는 기록',
  review_unfiled_hint: '갈피나 출처를 붙이면 나중에 찾을 수 있습니다',
  review_leave: '이대로 두기',
  review_empty: '검토할 기록 없음',
  review_dusty: '오래 안 읽은 기록',

  // ─── 수집함·표 ───
  inbox_title: '수집함',
  inbox_unfiled: (n: number) => `미분류 ${n}`,
  records_title: '기록',
  records_filter_type: '유형',
  records_filter_format: '형식',
  records_filter_tag: '갈피',
  records_count: (n: number) => `${n}건`,
  format_book: '책',
  format_video: '영상',
  format_article: '글',
} as const;
